import type { Metadata } from "next";
import { Figtree, Space_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { ReactQueryClientProvider } from "@/providers/ReactQueryProvider";
import { Toaster } from "@/components/ui/sonner"

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

const spaceMono = Space_Mono({
  variable: "--font-spacemono",
  weight: ["400", "700"],
  display: "swap",
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${figtree.variable} ${spaceMono.variable} antialiased dark`}
      >
        <ReactQueryClientProvider>
          <SidebarProvider>
            {children}
            <Toaster />
          </SidebarProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
